### ISSUE TITLE
Getting error while running the wppp.rb

### ISSUE THREAD

**Issue by ghost** [FireFart/WordpressPingbackPortScanner#11]
I was running `ruby wppps.rb -t http://target.com/xmlrpc.php https://target.com/xmlrpc.php -v ` and got this error : 

```
[ERROR] Url https://target.com/ does not provide a XML-RPC url
Trace :
wppps.rb:98:in `get_xml_rpc_url'
wppps.rb:266:in `block in <main>'
wppps.rb:262:in `each'
wppps.rb:262:in `<main>'
```
I am not sure whether I am using correct syntax or not. Would you please guide me? Moreover, the website is on the latest version of WordPress 5.3.4 with xmlrpc.php enabled on it.

ruby -v  : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]  
 
gem list : 

*** LOCAL GEMS ***
```
activesupport (6.0.3.4)
addressable (2.7.0)
atomic (1.1.16)
benchmark (default: 0.1.0)
bigdecimal (default: 2.0.0)
bundler (2.1.4)
cgi (default: 0.1.0)
cms_scanner (0.12.1)
concurrent-ruby (1.1.6)
concurrent-ruby-edge (0.6.0)
csv (default: 3.1.2)
date (default: 3.0.0)
dbm (default: 1.1.0)
delegate (default: 0.1.0)
did_you_mean (default: 1.4.0)
etc (default: 1.1.0)
ethon (0.9.0)
fcntl (default: 1.0.0)
ffi (1.12.2)
fiddle (default: 1.0.0)
fileutils (default: 1.4.1)
forwardable (default: 1.3.1)
gdbm (default: 2.1.0)
get_process_mem (0.2.5)
getoptlong (default: 0.1.0)
i18n (1.8.5)
io-console (default: 0.5.6)
ipaddr (default: 1.2.2)
irb (default: 1.2.6)
json (default: 2.3.0)
logger (default: 1.4.2)
matrix (default: 0.2.0)
mime-types (3.3.1)
mime-types-data (3.2015.1120)
minitest (5.13.0)
mutex_m (default: 0.1.0)
net-pop (default: 0.1.0)
net-smtp (default: 0.1.0)
net-telnet (0.1.1)
nokogiri (1.10.9)
observer (default: 0.1.0)
open3 (default: 0.1.0)
openssl (default: 2.1.2)
opt_parse_validator (1.9.2)
ostruct (default: 0.2.0)
pkg-config (1.4.4)
power_assert (1.1.7)
prime (default: 0.1.1)
pstore (default: 0.1.0)
psych (default: 3.1.0)
public_suffix (4.0.3)
racc (default: 1.4.16)
rake (13.0.1)
rdoc (default: 6.2.1)
readline (default: 0.0.2)
readline-ext (default: 0.1.0)
reline (default: 0.1.5)
rexml (default: 3.2.3)
rss (default: 0.2.8)
ruby-progressbar (1.10.1)
sdbm (default: 1.0.0)
singleton (default: 0.1.0)
stringio (default: 0.1.0)
strscan (default: 1.0.3)
test-unit (3.3.5)
thread_safe (0.3.6)
timeout (default: 0.1.0)
tracer (default: 0.1.0)
typhoeus (1.4.0)
tzinfo (1.2.6)
uri (default: 0.10.0)
webrick (default: 1.6.0)
wpscan (3.8.10)
xmlrpc (0.3.0)
yajl-ruby (1.4.1)
yaml (default: 0.1.0)
zeitwerk (2.2.2)
zlib (default: 1.1.0)
```

**Comment by ghost** [comment]
Tell me if this is the correct syntax or not : 

`ruby wppps.rb -t -a https://target.com/xmlrpc.php https://target.com/some-blog/`       

and

`ruby wppps.rb -t -a https://target.com/ https://target.com/some-blog/  `

Still same error.

**Comment by firefart** [comment]
`[ERROR] Url https://target.com/ does not provide a XML-RPC url` says it all
